### ISSUE TITLE
[CRITICAL] accidental docker-compose down leads to inability to recover current state of PKC intuitively 

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/micro-PKC#10]
if you do docker-container up you will have a not installed PKC and lost access to it.
You need to re-run the setup to recover access to your mediawiki container (the data will still be there because the mount point contains the persistent DB).

Solution approaches:
Document well how to recover - e.g. rerunning the setup.sh
Making it impossible to interact this way : Best would be if docker-compose commands could not even be run or are not exposed.

**Comment by rht** [comment]
Fixed in https://github.com/FantasticoFox/micro-PKC/commit/6821989e0381a2be8f8406585c4cfa0f3313fbaf and https://github.com/FantasticoFox/micro-PKC/commit/d60287b17f50aceac4d7bc800b2f12b45bcc58c5. Basically, the configs are now persisted in the backup/ folder.
