### ISSUE TITLE
[Install][Content] Changing the way the content is added to the PKC

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/micro-PKC#16]
Requires to modify the install_pkc.sh to add a loop which is pulling in the content from a seperate repository 
https://github.com/FantasticoFox/PKC-Content which holds all the content pages which explain how to use the pkc.

There should be an install option added which allows us to install the PKC empty (without pre-population). 
Perspective we will have different content-packages available for different use-cases which can be selected by flag.

**Comment by FantasticoFox** [comment]
Current script structure which needs modification

install_pkc.sh has this line
# Update sidebar 
php maintenance/edit.php -s "Use PKC sidebar" -u Admin MediaWiki:Sidebar < aqua/PKC-Content/sidebar.wiki

# Populate a page 
php maintenance/edit.php -a -u Admin "Moores Law" < aqua/PKC-Content/MooresLaw.wiki
I think it needs to be a loop which reads all the documents and creates the pages accordingly.

**Comment by Luan-vP** [comment]
Implemented in https://github.com/FantasticoFox/micro-PKC/pull/30
